// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // await Firebase.initializeApp(
  // options: DefaultFirebaseOptions.currentPlatform,
  // );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqeaWmHBUmzKIdQAF50JRl9ZK_l-q33Q8',
    appId: '1:79950976245:web:65130be950ede8837e61bc',
    messagingSenderId: '79950976245',
    projectId: 'flash-chat-2f68d',
    authDomain: 'flash-chat-2f68d.firebaseapp.com',
    storageBucket: 'flash-chat-2f68d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJY-7j52JNNJnpj0jbjghMFvnIkx2HYOE',
    appId: '1:79950976245:android:e9f6c28535c9d0bc7e61bc',
    messagingSenderId: '79950976245',
    projectId: 'flash-chat-2f68d',
    storageBucket: 'flash-chat-2f68d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMct3BZPaySQ-m9PkSjTHjGdNgdNX0e0',
    appId: '1:79950976245:ios:6d961ac72d62cf8c7e61bc',
    messagingSenderId: '79950976245',
    projectId: 'flash-chat-2f68d',
    storageBucket: 'flash-chat-2f68d.appspot.com',
    iosClientId: '79950976245-3et1ect4fk1k38mk3hf4hba5pnavfdjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMct3BZPaySQ-m9PkSjTHjGdNgdNX0e0',
    appId: '1:79950976245:ios:6d961ac72d62cf8c7e61bc',
    messagingSenderId: '79950976245',
    projectId: 'flash-chat-2f68d',
    storageBucket: 'flash-chat-2f68d.appspot.com',
    iosClientId: '79950976245-3et1ect4fk1k38mk3hf4hba5pnavfdjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
